<?php

namespace AppBundle\Repository;

/**
 * ArtStyleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArtStyleRepository extends \Doctrine\ORM\EntityRepository
{
}
